// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RushAg.Shared
{
    public partial class TodoItem
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        [StringLength(150)]
        [Required]
        public string Name { get; set; }
        [StringLength(500)]
        public string Notes { get; set; }
        [Display(Name = "Complete ?")]
        public bool IsComplete { get; set; } = false;
        public DateTime? CompleteDate { get; set; }
        public DateTime CreateDate { get; set; } = DateTime.Now;

        public IList<TodoSteps> Steps { get; } = new List<TodoSteps>();
    }
}