// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace RushAg.Core.Entities;

public partial class TodoItem
{
    public long TodoItemId { get; set; }
    public string Name { get; set; }
    public string Notes { get; set; }
    public bool IsComplete { get; private set; } = false;
    public DateTime? CompleteDate { get; set; }
    public DateTime CreateDate { get; set; } = DateTime.Now;

    private List<TodoStep> _steps = new List<TodoStep>();
    public IEnumerable<TodoStep> Steps => _steps.AsReadOnly();

    public TodoItem(string name)
    {
        if (string.IsNullOrEmpty(name))
            throw new ArgumentNullException(nameof(name));

        Name = name;
    }

    public void AddStep(TodoStep newStep)
    {
        if (newStep == null)
            throw new ArgumentNullException(nameof(newStep));

        _steps.Add(newStep);
    }

    public void UpdateStep(string newName, string newNotes)
    {
        if (string.IsNullOrEmpty(newName))
            throw new ArgumentNullException(nameof(newName));
        if(string.IsNullOrEmpty(newNotes))
            throw new ArgumentNullException(nameof(newNotes));

        Name = newName;
        Notes = newNotes;
    }

    public void SetIsComplete(bool isComplete)
    {
        if (isComplete)
        {
            IsComplete = true;
            CompleteDate = DateTime.Now;
        }
        else
        {
            IsComplete = false;
            CompleteDate = null;
        }
    }
}